config/routes.rb
Rails.application.routes.draw do
  get '/recipes/public', to: 'recipes#public'
  get '/foods/new(/:recipe_id)', to: 'foods#new'
  get '/general_shopping_list', to: 'shopping_list#index'
  resources :recipe_foods
  resources :foods
  resources :recipes
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'foods#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.includes(recipe_foods: [:food])
  end

  def public
    @recipes = Recipe.includes(recipe_foods: [:food]).where(public: true).order(created_at: :desc)
    render :index
  end

  # GET /recipes/1 or /recipes/1.json
  def show; end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = current_user.recipes.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, class: "text-center container") do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block", class: "form-label"  %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block", class: "form-label"  %>
    <%= form.number_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block", class: "form-label"  %>
    <%= form.number_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block", class: "form-label"  %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "padding-right: 10px"  %>
    <%= form.check_box :public %>
  </div>

  <div class="m-3">
    <%= form.submit "Create", class: "btn btn-success" %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>" class="container">
  <p>
    <strong>Preparation time:</strong>
    <%= recipe.preparation_time %>
  </p>

  <p>
    <strong>Cooking time:</strong>
    <%= recipe.cooking_time %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>Public:</strong>
    <input type="checkbox" disabled <%= "checked" if recipe.public %>>
  </p>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<div class="container d-flex justify-content-between px-5 py-3">
  <h2>Recipes</h2>

  <% if user_signed_in? %>
      <%= link_to "New Recipe", new_recipe_path, class: 'btn btn-primary align-self-center' %>
  <% end %> 
</div>

<div id="recipes" class="container">
  <% @recipes.each do |recipe| %>
    <div class="border border-info row p-3 m-3">
      <div class="col-4">
        <h2><%= recipe.name %></h2>
        <div class="d-flex gap-3">
          <% if user_signed_in? && current_user.id == recipe.user_id %>
            <%= button_to "Remove", recipe, method: :delete, class: 'btn btn-danger'%>
            <%= link_to "Edit", edit_recipe_path(recipe), class: 'btn btn-info' %>
          <% end %>
          <% if (current_user && current_user.id == recipe.user_id) || recipe.public %>
              <%= link_to "Details", recipe, class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
      <div class="col-4">
        <h2>Description:</h2>
        <p><%= recipe.description %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1 class="text-center">New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div class="text-center">
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<h2 class="text-center"><%= @recipe.name %></h2>
<%= render @recipe %>

<div class="container">

  <div class="d-flex justify-content-between py-4">
    <%= link_to "General Shopping List", general_shopping_list_path, class: 'btn btn-primary' %>

    <% if user_signed_in? && current_user.id == @recipe.user_id %>
      <%= link_to "Add ingredient", new_food_path(recipe_id: @recipe.id), class: 'btn btn-primary' %>
    <% end %>
  </div>


  <div>
    <table class="table table-bordered table-striped">
      <thead>
        <tr class="text-center">
          <th>Food</th>
          <th>Quantity</th>
          <th>Value</th>
          <% if current_user && current_user.id == @recipe.user_id %>
            <th>Actions</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% if @recipe.recipe_foods.length === 0 %>
        <tr class="text-center fw-bold">
          <td colspan="4">No ingredients found</td>
        </tr>
        <% else %>
          <% @recipe.recipe_foods.each do |ing| %>
            <tr class="text-center">
              <td><%= ing.food.name %></td>
              <td><%= ing.Quantity %> <%= ing.food.measurement_unit %></td>
              <td><%= ing.food.price * ing.Quantity %></td>
              <% if current_user && current_user.id == @recipe.user_id %>
                <td class="d-flex gap-3 justify-content-center">
                  <%= link_to "Modify", edit_recipe_food_path(ing), class: 'btn btn-primary'%>
                  <%= button_to "Delete", ing, method: :delete, class: 'btn btn-danger'%>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="text-center">
  <%= link_to "Back to recipes", recipes_path %>
</div>