config/routes.rb
Rails.application.routes.draw do
  get '/recipes/public', to: 'recipes#public'
  get '/foods/new(/:recipe_id)', to: 'foods#new'
  get '/general_shopping_list', to: 'shopping_list#index'
  resources :recipe_foods
  resources :foods
  resources :recipes
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'foods#index'
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]
  before_action :set_recipe, only: %i[new]

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    if !food_recipe_params[:recipe_id] || food_recipe_params[:food_id] == 'Add new food'
      @food = current_user.foods.new(food_params)
      respond_to do |format|
        food_create_helper(format, @food)
      end
    end
    return unless food_recipe_params[:recipe_id]

    new_food = food_recipe_params[:food_id] == 'Add new food'
    recipefood = RecipeFood.create(food_id: new_food ? @food.id : food_recipe_params[:food_id],
                                   recipe_id: food_recipe_params[:recipe_id], Quantity: food_recipe_params[:Quantity])
    return if food_recipe_params[:food_id] == 'Add new food'

    @food = Food.find(food_recipe_params[:food_id])
    respond_to do |format|
      format.html { redirect_to recipe_url(recipefood.recipe), notice: 'Food was successfully added to the recipe.' }
      format.json { render :show, status: :created, location: @food }
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id]) if params[:recipe_id]
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end

  # Only allow a list of trusted parameters through with recipe id.
  def food_recipe_params
    params.require(:food).permit(:recipe_id, :Quantity, :food_id)
  end

  def food_create_helper(format, food)
    if food.save
      format.html { redirect_to foods_url, notice: 'Food was successfully created.' }
      format.json { render :show, status: :created, location: food }
    else
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: food.errors, status: :unprocessable_entity }
    end
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Measurement unit:</strong>
    <%= food.measurement_unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= form_with(model: food, class: "text-center container") do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% unless @recipe.nil? %>
    <div>
      <%= form.select(:food_id, ['Add new food'] + Food.where(user_id: current_user.id).collect {|f| [f.name, f.id]}, selected: Food.first.id) %>
    </div>
  <% end %>

    <div id='food-form-group' class=<%="#{'d-none' unless @recipe.nil? }"%>>
      <div>
        <%= form.label :name, style: "display: block", class: "form-label" %>
        <%= form.text_field :name %>
      </div>

      <div>
        <%= form.label :measurement_unit, style: "display: block", class: "form-label" %>
        <%= form.text_field :measurement_unit %>
      </div>

      <div>
        <%= form.label :price, style: "display: block", class: "form-label" %>
        <%= form.number_field :price %>
      </div>
    </div>

  <% unless @recipe.nil? %>
    <div>
      <%= form.hidden_field :recipe_id, value: @recipe.nil? ? nil : @recipe.id %>
    </div>
  <% end %>

  <% unless @recipe.nil? %>
    <div>
      <%= form.label :Quantity, style: "display: block" %>
      <%= form.number_field :Quantity %>
    </div>
  <% end %>

  <div class="m-3">
    <%= form.submit "Create", class: "btn btn-success" %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<div class="container d-flex justify-content-between px-5 py-3">
  <h2>Foods</h2>

  <% if user_signed_in? %>
      <%= link_to "New food", new_food_path, class: 'btn btn-primary align-self-center' %>
  <% end %> 
</div>

<div id="foods">
  <div class="container">
    <table class="table table-bordered table-striped">
      <thead>
        <tr class="text-center">
          <th>Name</th>
          <th>Measurement unit</th>
          <th>Unit Price</th>
          <% if user_signed_in? %>
            <th>Actions</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% if @foods.length === 0 %>
          <tr class="text-center fw-bold">
            <td colspan="4">No foods found</td>
          </tr>
        <% else %>
          <% @foods.each do |food| %>
            <tr class="text-center">
              <td><%= food.name %></td>
              <td><%= food.measurement_unit %></td>
              <td><%= food.price %> $</td>
              <% if current_user && current_user.id == food.user_id %>
                <td class="d-flex gap-3 justify-content-center">
                  <%= button_to "Remove", food, method: :delete, class: 'btn btn-danger' %>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/foods/new.html.erb
<h1 class="text-center">New food</h1>

<%= render "form", food: @food %>

<br>

<div class="text-center">
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<%= render @food %>

<div>
<% if user_signed_in? && current_user.id == @food.user_id %>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <% end %>
  <%= link_to "Back to foods", foods_path %>

<% if user_signed_in? && current_user.id == @food.user_id %>
  <%= button_to "Destroy this food", @food, method: :delete %>
  <% end %>
</div>