config/routes.rb
Rails.application.routes.draw do
  get '/recipes/public', to: 'recipes#public'
  get '/foods/new(/:recipe_id)', to: 'foods#new'
  get '/general_shopping_list', to: 'shopping_list#index'
  resources :recipe_foods
  resources :foods
  resources :recipes
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'foods#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> 
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">RecipeApp</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mb-2 mb-lg-0 d-flex w-100">
            <li class="nav-item">
              <%= link_to "Foods", foods_path, class: 'nav-link'%>
            </li>
            <li class="nav-item">
              <%= link_to "Recipes", recipes_path, class: 'nav-link'%>
            </li>
            <li class="nav-item">
              <%= link_to "Public Recipes", recipes_public_path, class: 'nav-link'%>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Shopping List", general_shopping_list_path, class: 'nav-link'%>
              </li>
            <% end %>
            <% if user_signed_in? %>
              <li class="nav-item ms-auto">
                <%= button_to "Sign out", destroy_user_session_path, :method => :delete, class: 'btn btn-danger'%>
              </li>
            <% end %>
            <% unless user_signed_in? %>
              <li class="nav-item ms-auto">
                <%= link_to "Register", new_user_registration_path, class: 'nav-link'%>
              </li>
              <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: 'nav-link'%>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <% flash.each do |type, msg| %> <div> <%= msg %> </div> <% end %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> 
  </body>
</html>